apiVersion: apps/v1
kind: Deployment
metadata:
  name: stihl8
spec:
  selector:
    matchLabels:
      app: stihl8
  template:
    metadata:
      #namespace: production-ns
      labels:
        app: stihl8 
    spec:
      containers:
      #- image: teststihlcustomacr.azurecr.io/stihl8
      - image: drupal:7.89-php7.4-apache-buster
        name: stihl8
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: database
        - name: DATABASE_HOST
          value: mariadb
        ports:
        - containerPort: 80
        volumeMounts:
          - name: stihl8-pvc
            mountPath: /web-assets
      volumes:
        - name: stihl8-pvc
          persistentVolumeClaim:
            claimName: stihl8-pvc