apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
spec:
  selector:
    matchLabels:
      app: stihl7
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: stihl7
    spec:
      containers:
      - name: stihl7
        image: stihl7
        env:
          # Use secret in real usage
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupalsecrets
              key: database
        - name: DATABASE_HOST
          value: mariadb
