apiVersion: apps/v1
kind: Deployment
metadata:
  name: stihl7
spec:
  selector:
    matchLabels:
      app: stihl7
  template:
    metadata:
      labels:
        app: stihl7 
    spec:
      containers:
      - image: teststihlcustomacr.azurecr.io/stihl7
        name: stihl7
        ports:
        - containerPort: 80