# Pipeline generated template for reference. Do not change, do not delete.
apiVersion : apps/v1
kind: Deployment
metadata:
  name: stihl8 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stihl8
  template:
    metadata:
      labels:
        app: stihl8 
    spec:
      containers:
        - name: stihl8 
          image: teststihlcustomacr.azurecr.io/stihl8
          ports:
          - containerPort: 80