apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-bluepresley-com
spec:
  selector:
    matchLabels:
      app: test-bluepresley-com
  template:
    metadata:
      labels:
        app: test-bluepresley-com 
    spec:
      containers:
      - image: teststihlcustomacr.azurecr.io/stihl7
        name: stihl7
        ports:
        - containerPort: 80