apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stihl8-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aks-file-share-custom-sc-csi
  resources:
    requests:
      storage: 10Gi