# Pipeline generated template for reference. Do not change, do not delete.
apiVersion: v1
kind: Service
metadata:
    name: stihl8
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: stihl8