apiVersion: v1
kind: Service
metadata:
  name: www-bluepresley-com-svc
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: www-bluepresley-com-app
  type: ClusterIP