<?php
/**
 * @file
 * menu_link.36d59b72fee53ab0ef17a0ee5f8767189e5a9b6f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/date',
  'link_title' => 'Date API',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for modules the use the Date API.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/date',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
