<?php
/**
 * @file
 * menu_link.f6dd1d4e633639d36c197de10555a1bed1570240.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/x_originating_ip',
  'link_title' => 'X-Originating-IP',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Use alternative headers for outgoing email identifying the originating IP address of the remote client.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/system/x_originating_ip',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
