<?php
/**
 * @file
 * menu_link.4b2321fe8c0d3e7c126bb0c2fbee79321dc06efe.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/field/info',
  'link_title' => 'Field info',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View fields information across the whole site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'devel/field/info',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
