<?php
/**
 * @file
 * menu_link.a78baecc21d8d13b39efd6fd18aa5ad2962485a8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/search_api',
  'link_title' => 'Search API',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Create and configure search engines.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/search/search_api',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
