<?php
/**
 * @file
 * menu_link.2af77199054070671173ab0826ca97fc8477a683.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/42',
  'link_title' => 'Concrete Cutter',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Concrete Cutter',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'b6e43cfdbace347ed0dd243289f5d6e238fbe7e7',
);

$dependencies = array(
  'menu_link.b6e43cfdbace347ed0dd243289f5d6e238fbe7e7' => 'menu_link.b6e43cfdbace347ed0dd243289f5d6e238fbe7e7',
);

$optional = array();

$modules = array();
