<?php
/**
 * @file
 * menu_link.a3eea87d2fa47a3e8b28e88ed65f53a4fcd49ba8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/38',
  'link_title' => 'Kombi Attachments',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Kombi Attachments',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$dependencies = array(
  'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f' => 'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$optional = array();

$modules = array();
