<?php
/**
 * @file
 * menu_link.40457f49ccea290e0f41649711715cd009ab6898.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/orders/add',
  'link_title' => 'Create an order',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Create a new order.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/orders/add',
  'parent_identifier' => 'ec7ecd22e5d3c24ea0890dd26f0ae6fb773e9b6e',
);

$dependencies = array(
  'menu_link.ec7ecd22e5d3c24ea0890dd26f0ae6fb773e9b6e' => 'menu_link.ec7ecd22e5d3c24ea0890dd26f0ae6fb773e9b6e',
);

$optional = array();

$modules = array();
