<?php
/**
 * @file
 * menu_link.78da529aecb057f155447c89eaef990088f294cf.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/slack',
  'link_title' => 'Slack',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure slack module.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/services/slack',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
