<?php
/**
 * @file
 * menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/6',
  'link_title' => 'Battery-Powered Products',
  'menu_name' => 'menu-product-categories',
  'weight' => '-49',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery-Powered Products',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
