<?php
/**
 * @file
 * menu_link.2fe8c0f9248161c7f9296d1cb0d5a4058f7328a7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/banner-image',
  'link_title' => 'Banner Image',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Banner image used on the homepage, or other places tbd.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'node/add/banner-image',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
