<?php
/**
 * @file
 * menu_link.ca4ce02418c8d173ea972ec84097a10e26df6691.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/10',
  'link_title' => 'Sprayers',
  'menu_name' => 'menu-product-categories',
  'weight' => '-44',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Sprayers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
