<?php
/**
 * @file
 * menu_link.bfcfc44f84594ed7a42870d0ffe7b06ed4aedb68.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'cart',
  'link_title' => 'My Cart',
  'menu_name' => 'user-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View my cart',
    ),
  ),
  'router_path' => 'cart',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.user_menu' => 'menu.user_menu',
);

$optional = array();

$modules = array();
