<?php
/**
 * @file
 * menu_link.7445badee0962a1c96be3a1490c3d70de99280bc.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/devel',
  'link_title' => 'Devel settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Helper functions, pages, and blocks to assist Drupal developers. The devel blocks can be managed via the <a href="/admin/structure/block">block administration</a> page.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/devel',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
