<?php
/**
 * @file
 * menu_link.5d5791e97fef78334b587d2383ba8e286fb1b503.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/fp-templates',
  'link_title' => 'FusionPro Template Configurations',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage template configurations',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/services/fp-templates',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
