<?php
/**
 * @file
 * menu_link.02a7ad14d10d750c0b37a8bcea1f0275fac80af8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/21',
  'link_title' => 'Battery Chain Saws',
  'menu_name' => 'menu-product-categories',
  'weight' => '3',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery Chain Saws',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$dependencies = array(
  'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f' => 'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$optional = array();

$modules = array();
