<?php
/**
 * @file
 * menu_link.b85de4ee78a9892f40ef42061b9aca8ae9e721af.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/hide-fatal-error',
  'link_title' => 'Hide Fatal Errors',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Redirect to an error page on PHP fatal error.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/hide-fatal-error',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
