<?php
/**
 * @file
 * menu_link.dc1758c79385781e6870432521757e3f1449d1c5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/diff',
  'link_title' => 'Diff',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Diff settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/content/diff',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
