<?php
/**
 * @file
 * menu_link.72346d63672172a6548701f411810c8416e0cca7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/role_grants',
  'link_title' => 'Role grants report',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View changes to role assignments for users.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/reports/role_grants',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
