<?php
/**
 * @file
 * menu_link.b91dbccc8f4e8d58a90a1819e48ffd7f1832b042.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/fusion_pro',
  'link_title' => 'FusionPro',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Setup the connection settings for talking to a FusionPro server.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/services/fusion_pro',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
