<?php
/**
 * @file
 * menu_link.2739d62ea738f0dc74057a825214d1c48a961994.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/47',
  'link_title' => 'Pressure Washers',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Pressure Washers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '442257a210a458760e51f75a9c28883f96f401f0',
);

$dependencies = array(
  'menu_link.442257a210a458760e51f75a9c28883f96f401f0' => 'menu_link.442257a210a458760e51f75a9c28883f96f401f0',
);

$optional = array();

$modules = array();
