<?php
/**
 * @file
 * menu_link.fbecfde2ee97048742df174ec230006fce8843a5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/27',
  'link_title' => 'Brushcutter/Clearing Saw',
  'menu_name' => 'menu-product-categories',
  'weight' => '-49',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Brushcutter/Clearing Saw',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ffbe2501719ec189b88398837891ccef024e3ea9',
);

$dependencies = array(
  'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9' => 'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9',
);

$optional = array();

$modules = array();
