<?php
/**
 * @file
 * menu_link.c8b884a3be9cd2e3170f4ed374328846bb28b5b7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/revision-all',
  'link_title' => 'Revision All',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the revisioning of content types.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/content/revision-all',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
