<?php
/**
 * @file
 * menu_link.f7d98e9704f9694ed4069cd5a00c7f499828a923.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/diskfree',
  'link_title' => 'Diskfree',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure minimum alert threshold and e-mail destination.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/system/diskfree',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
