<?php
/**
 * @file
 * menu_link.38e262870ff490a7d612d6221751a5b9e1be08e6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/37',
  'link_title' => 'KombiMotors',
  'menu_name' => 'menu-product-categories',
  'weight' => '1',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'KombiMotors',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$dependencies = array(
  'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f' => 'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$optional = array();

$modules = array();
