<?php
/**
 * @file
 * menu_link.bbb2d0c9ad83084d859c4b2da789e5b30d924ce3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/reports',
  'link_title' => 'Reports',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View reports for your store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/reports',
  'parent_identifier' => 'fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$dependencies = array(
  'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5' => 'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$optional = array();

$modules = array();
