<?php
/**
 * @file
 * menu_link.5bae98713c38ade3faf9fc17aabd83e0c89e5ebc.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/product-pricing',
  'link_title' => 'Product pricing rules',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Enable and configure product pricing rules and pre-calculation.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/product-pricing',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
