<?php
/**
 * @file
 * menu_link.e18a46a57a59bd9b7eddfc832ecf3e5c2eda47bc.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/39',
  'link_title' => 'YARD BOSS',
  'menu_name' => 'menu-product-categories',
  'weight' => '2',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'YARD BOSS',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$dependencies = array(
  'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f' => 'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$optional = array();

$modules = array();
