<?php
/**
 * @file
 * menu_link.48d424cfaba66a026a4f7624ebaa945a690fdc20.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/stihl/next-year-pricing',
  'link_title' => 'Enable Next Year Pricing',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configuration setting to enable next year price option.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/stihl/next-year-pricing',
  'parent_identifier' => '9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$dependencies = array(
  'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05' => 'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$optional = array();

$modules = array();
