<?php
/**
 * @file
 * menu_link.c9ab906624db0630d1322e078ffc3f8328269249.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/24',
  'link_title' => 'Battery Accessories – Chargers',
  'menu_name' => 'menu-product-categories',
  'weight' => '2',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery Accessories – Chargers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$dependencies = array(
  'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f' => 'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$optional = array();

$modules = array();
