<?php
/**
 * @file
 * menu_link.359c4c5668293346852f45eb799fa6efea5d1a3e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/48',
  'link_title' => 'Brushcutter',
  'menu_name' => 'menu-product-categories',
  'weight' => '-50',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Brushcutter',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ffbe2501719ec189b88398837891ccef024e3ea9',
);

$dependencies = array(
  'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9' => 'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9',
);

$optional = array();

$modules = array();
