<?php
/**
 * @file
 * menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/13',
  'link_title' => 'Multi-Task Tools',
  'menu_name' => 'menu-product-categories',
  'weight' => '-41',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Multi-Task Tools',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
