<?php
/**
 * @file
 * menu_link.ee41b0cb0c704e093cc35175434551a0d125806d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/19',
  'link_title' => 'Electric Chain Saws',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Electric Chain Saws',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'db82cc9be767c7315003cc93631177f94d13b6de',
);

$dependencies = array(
  'menu_link.db82cc9be767c7315003cc93631177f94d13b6de' => 'menu_link.db82cc9be767c7315003cc93631177f94d13b6de',
);

$optional = array();

$modules = array();
