<?php
/**
 * @file
 * menu_link.ffbe2501719ec189b88398837891ccef024e3ea9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/7',
  'link_title' => 'Trimmers and Brushcutters',
  'menu_name' => 'menu-product-categories',
  'weight' => '-47',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Trimmers and Brushcutters',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
