<?php
/**
 * @file
 * menu_link.6e05437194da9493e221fc0055c67b8d9e8ad1d0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/line-items',
  'link_title' => 'Line item types',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage line item types for your store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/line-items',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
