<?php
/**
 * @file
 * menu_link.bd9c70cd2dc979c44ff0605623e247a0f963bf39.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/webform',
  'link_title' => 'Webform settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Global configuration of webform functionality.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/content/webform',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
