<?php
/**
 * @file
 * menu_link.c473f43dfb799ed3da16b90c2feea1f0b21fc8b3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/order',
  'link_title' => 'Generate orders',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of orders.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/order',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
