<?php
/**
 * @file
 * menu_link.63aabfc2be9a5d1f8f8fbf7c81422641b8f5f2d8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/no_autocomplete',
  'link_title' => 'No Autocomplete',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Turn on autocomplete=off for key user forms',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/no_autocomplete',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
