<?php
/**
 * @file
 * menu_link.bc1d595a72fc71f470997df490f8114866cecc3b.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/flood-control',
  'link_title' => 'Flood control',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Control flood control options for failed login attempts, contact forms, etc.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/system/flood-control',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
