<?php
/**
 * @file
 * menu_link.7fe6ea3a30814898ddd3acc004c7f87e4bf053f8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/16',
  'link_title' => 'Augers and Drills',
  'menu_name' => 'menu-product-categories',
  'weight' => '-38',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Augers and Drills',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
