<?php
/**
 * @file
 * menu_link.0c6f6cd09e8bf79a653884626de8712ddfde842c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/libraries',
  'link_title' => 'Libraries',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'An overview of libraries installed on this site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/reports/libraries',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
