<?php
/**
 * @file
 * menu_link.7da921a623bb80c96c21d5f470ed190080488f93.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/26',
  'link_title' => 'Gas Trimmers',
  'menu_name' => 'menu-product-categories',
  'weight' => '-48',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gas Trimmers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ffbe2501719ec189b88398837891ccef024e3ea9',
);

$dependencies = array(
  'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9' => 'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9',
);

$optional = array();

$modules = array();
