<?php
/**
 * @file
 * menu_link.57f8c474b9dcd6fc2c84cc6c732c67f8cd470d16.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/slack/config',
  'link_title' => 'Configuration',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Adjust slack settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/services/slack/config',
  'parent_identifier' => '78da529aecb057f155447c89eaef990088f294cf',
);

$dependencies = array(
  'menu_link.78da529aecb057f155447c89eaef990088f294cf' => 'menu_link.78da529aecb057f155447c89eaef990088f294cf',
);

$optional = array();

$modules = array();
