<?php
/**
 * @file
 * menu_link.9733df7a4dcb0fa70abf6103e2cd5a44c4634118.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/35',
  'link_title' => 'Hedge Trimmers',
  'menu_name' => 'menu-product-categories',
  'weight' => '1',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Hedge Trimmers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '785e56549281adf49a8a4025c5fe14d17f05610a',
);

$dependencies = array(
  'menu_link.785e56549281adf49a8a4025c5fe14d17f05610a' => 'menu_link.785e56549281adf49a8a4025c5fe14d17f05610a',
);

$optional = array();

$modules = array();
