<?php
/**
 * @file
 * menu_link.4b74febc23489e00a1efab4619dda0720283e484.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/product-display',
  'link_title' => 'Product Display',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'node/add/product-display',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
