<?php
/**
 * @file
 * menu_link.e02b40de57a5fad723d64f97f716a686e5f56450.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/password_policy',
  'link_title' => 'Password policies',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configures policies for user account passwords.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/password_policy',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
