<?php
/**
 * @file
 * menu_link.28f59f0c173a066e31f5efd5fd108d50c68bf154.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/31',
  'link_title' => 'Gas Blowers Shredder Vacs',
  'menu_name' => 'menu-product-categories',
  'weight' => '-48',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gas Blowers Shredder Vacs',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '6432591b5da5c73991566e64cb9fa684e56051a4',
);

$dependencies = array(
  'menu_link.6432591b5da5c73991566e64cb9fa684e56051a4' => 'menu_link.6432591b5da5c73991566e64cb9fa684e56051a4',
);

$optional = array();

$modules = array();
