<?php
/**
 * @file
 * menu_link.35f1587720aba88c916f0e62fc7e90e771b5accc.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/49',
  'link_title' => 'Gas Backpack Sprayer',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gas Backpack Sprayer',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ca4ce02418c8d173ea972ec84097a10e26df6691',
);

$dependencies = array(
  'menu_link.ca4ce02418c8d173ea972ec84097a10e26df6691' => 'menu_link.ca4ce02418c8d173ea972ec84097a10e26df6691',
);

$optional = array();

$modules = array();
