<?php
/**
 * @file
 * menu_link.442257a210a458760e51f75a9c28883f96f401f0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/18',
  'link_title' => 'Pressure Washers',
  'menu_name' => 'menu-product-categories',
  'weight' => '-36',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Pressure Washers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
