<?php
/**
 * @file
 * menu_link.5a6be75cc40dcd1b0ca6b10aca2466f3ba8ef65d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/stock',
  'link_title' => 'Stock management',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure stock management.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/stock',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
