<?php
/**
 * @file
 * menu_link.8f78ce93008f9d6fe735237eb5f738d8f3a69dff.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/products',
  'link_title' => 'Products',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage products and product types in the store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/products',
  'parent_identifier' => 'fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$dependencies = array(
  'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5' => 'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$optional = array();

$modules = array();
