<?php
/**
 * @file
 * menu_link.fd518b9962ea786021231878ab5650380b6b5fab.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/stihl-profiles',
  'link_title' => 'Stihl Distributor Profiles',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage branch/distributor profiles',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/stihl-profiles',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
