<?php
/**
 * @file
 * menu_link.1532db2db49de09a2a500e447081ee8ee0930298.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/40',
  'link_title' => 'YARD BOSS Attachments',
  'menu_name' => 'menu-product-categories',
  'weight' => '3',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'YARD BOSS Attachments',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$dependencies = array(
  'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f' => 'menu_link.06ed0d45e737cb5b207403d73cb50eb7ed1a421f',
);

$optional = array();

$modules = array();
