<?php
/**
 * @file
 * menu_link.44481c847b0e877dced2be1b822847baa2141567.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/administration/admin-menu',
  'link_title' => 'Administration menu',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Adjust administration menu settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/administration/admin-menu',
  'parent_identifier' => 'ada990f9339b55d703abdf1d3baae0268477fa51',
);

$dependencies = array(
  'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51' => 'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51',
);

$optional = array();

$modules = array();
