<?php
/**
 * @file
 * menu_link.65d46f0ea8fa97fb335d9188500cdc971c6636ad.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/entity/info',
  'link_title' => 'Entity info',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View entity information across the whole site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'devel/entity/info',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
