<?php
/**
 * @file
 * menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/products/add',
  'link_title' => 'Add a product',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Add a new product for sale.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/products/add',
  'parent_identifier' => '8f78ce93008f9d6fe735237eb5f738d8f3a69dff',
);

$dependencies = array(
  'menu_link.8f78ce93008f9d6fe735237eb5f738d8f3a69dff' => 'menu_link.8f78ce93008f9d6fe735237eb5f738d8f3a69dff',
);

$optional = array();

$modules = array();
