<?php
/**
 * @file
 * menu_link.513dff1d70c1e3de98f4dfe12defbe8d79caa919.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/12',
  'link_title' => 'Pole Pruners',
  'menu_name' => 'menu-product-categories',
  'weight' => '-42',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Pole Pruners',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
