<?php
/**
 * @file
 * menu_link.fb04b81a7f1da1c013e993c3a2b8f35558a09b21.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/43',
  'link_title' => 'Augers Drills',
  'menu_name' => 'menu-product-categories',
  'weight' => '-49',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Augers Drills',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '7fe6ea3a30814898ddd3acc004c7f87e4bf053f8',
);

$dependencies = array(
  'menu_link.7fe6ea3a30814898ddd3acc004c7f87e4bf053f8' => 'menu_link.7fe6ea3a30814898ddd3acc004c7f87e4bf053f8',
);

$optional = array();

$modules = array();
