<?php
/**
 * @file
 * menu_link.b0196c3ebe8cd7e22b15844ba00211e5a7544eb9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/44',
  'link_title' => 'Electric Units',
  'menu_name' => 'menu-product-categories',
  'weight' => '1',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Electric Units',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'db82cc9be767c7315003cc93631177f94d13b6de',
);

$dependencies = array(
  'menu_link.db82cc9be767c7315003cc93631177f94d13b6de' => 'menu_link.db82cc9be767c7315003cc93631177f94d13b6de',
);

$optional = array();

$modules = array();
