<?php
/**
 * @file
 * menu_link.ada990f9339b55d703abdf1d3baae0268477fa51.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/administration',
  'link_title' => 'Administration',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administration tools.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/administration',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
