<?php
/**
 * @file
 * menu_link.233bc99c8a3f5fa1034f2c13f992011bf923ebd9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/stihl/pricing-api',
  'link_title' => 'Pricing API Settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configuration settings for the pricing API.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/stihl/pricing-api',
  'parent_identifier' => '9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$dependencies = array(
  'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05' => 'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$optional = array();

$modules = array();
