<?php
/**
 * @file
 * menu_link.49224bfaf9248e555cfbde7cd7b3341296729ebe.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/workflow/workflow',
  'link_title' => 'Workflows',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage Workflows.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/workflow/workflow',
  'parent_identifier' => '1cf7f51f65269905dde8a74fac5c14380fdeedd7',
);

$dependencies = array(
  'menu_link.1cf7f51f65269905dde8a74fac5c14380fdeedd7' => 'menu_link.1cf7f51f65269905dde8a74fac5c14380fdeedd7',
);

$optional = array();

$modules = array();
