<?php
/**
 * @file
 * menu_link.cc5e27781798ca3c240d13ba445984ecc3a0c2c2.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/33',
  'link_title' => 'Sprayers',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Sprayers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ca4ce02418c8d173ea972ec84097a10e26df6691',
);

$dependencies = array(
  'menu_link.ca4ce02418c8d173ea972ec84097a10e26df6691' => 'menu_link.ca4ce02418c8d173ea972ec84097a10e26df6691',
);

$optional = array();

$modules = array();
