<?php
/**
 * @file
 * menu_link.fa8a2be1f271741c22fefb6d87b58a7df1e3f6b5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/email_confirm',
  'link_title' => 'Email change confirmation settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configuration of confirmation email sent to users who attempt to change their email address.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/email_confirm',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
