<?php
/**
 * @file
 * menu_link.59d5ba9a5bd65cbaf2268aa5115811988204bca5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/vocabs',
  'link_title' => 'Generate vocabularies',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of vocabularies. Optionally delete current vocabularies.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/vocabs',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
