<?php
/**
 * @file
 * menu_link.fd16faa793bc26716a959b93ede894ddac425d85.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/role_watchdog',
  'link_title' => 'Role watchdog',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Logs changes to user roles.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/role_watchdog',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
