<?php
/**
 * @file
 * menu_link.179233910aba286d8093f57ce6cc2f1c8b577aae.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/ldap',
  'link_title' => 'LDAP Configuration',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'LDAP authentication, authorization, provisioning, etc.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/ldap',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
