<?php
/**
 * @file
 * menu_link.1ffefa611d7ab1d83e1c12020e468751c9609579.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/23',
  'link_title' => 'Battery Accessories – Batteries',
  'menu_name' => 'menu-product-categories',
  'weight' => '1',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery Accessories – Batteries',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$dependencies = array(
  'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f' => 'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$optional = array();

$modules = array();
