<?php
/**
 * @file
 * menu_link.4d6587e5a172b848b4d9e56e839b0c23b986b6e4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/session_expire',
  'link_title' => 'Session expire',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for session expiry',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/system/session_expire',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
