<?php
/**
 * @file
 * menu_link.45788c426ba09783d23795b9df36a16e245b57f8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/autologout',
  'link_title' => 'Auto Logout',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer Auto Logout settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/autologout',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
