<?php
/**
 * @file
 * menu_link.db82cc9be767c7315003cc93631177f94d13b6de.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/4',
  'link_title' => 'Electric-Powered Products',
  'menu_name' => 'menu-product-categories',
  'weight' => '-48',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Electric-Powered Products',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
