<?php
/**
 * @file
 * menu_link.c16b89568f7b56dcd5244c42103311c1d9c832ee.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/reroute_email',
  'link_title' => 'Reroute Email',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Reroute emails to a test address.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/reroute_email',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
