<?php
/**
 * @file
 * menu_link.e146d713b1e5c06cd09d11a45023396b5198b8d9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/security-review',
  'link_title' => 'Security review',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Perform a review of the security of your site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/reports/security-review',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
