<?php
/**
 * @file
 * menu_link.056aa751fd60b1f3da7ea5b4765b4249a14886d1.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'charts/examples',
  'link_title' => 'Charts examples',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'charts/examples',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
