<?php
/**
 * @file
 * menu_link.a5082c02697dd37a6fcf43c5bb6293e30fc94da9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/payment-methods/add',
  'link_title' => 'Add a payment method rule',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Adds an additional payment method rule configuration.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/payment-methods/add',
  'parent_identifier' => '53f5a352ac9bf2dbb064492823ae50cb0f20cf3c',
);

$dependencies = array(
  'menu_link.53f5a352ac9bf2dbb064492823ae50cb0f20cf3c' => 'menu_link.53f5a352ac9bf2dbb064492823ae50cb0f20cf3c',
);

$optional = array();

$modules = array();
