<?php
/**
 * @file
 * menu_link.804cefa7a50c377812fb3384d4bb3adc3c0c0d64.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'orders/list',
  'link_title' => 'Hangtag Order History',
  'menu_name' => 'main-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Hangtag orders list',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'orders/list',
  'parent_identifier' => 'd5a2d69870717510ae152eae169a963cba521868',
);

$dependencies = array(
  'menu_link.d5a2d69870717510ae152eae169a963cba521868' => 'menu_link.d5a2d69870717510ae152eae169a963cba521868',
);

$optional = array();

$modules = array();
