<?php
/**
 * @file
 * menu_link.b093ba9cdd527f4417cb208f8fc0168d5b11aa9d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/views_calc',
  'link_title' => 'Views Calc',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Set Views Calc fields and columns.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/views_calc',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
