<?php
/**
 * @file
 * menu_link.55582448f857d8119b1d950aeb6bfb0026427bae.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/scheduler',
  'link_title' => 'Scheduler',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure settings for scheduled publishing and unpublishing, run the lightweight cron and check your servers clock time.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/content/scheduler',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
