<?php
/**
 * @file
 * menu_link.53f5a352ac9bf2dbb064492823ae50cb0f20cf3c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/payment-methods',
  'link_title' => 'Payment methods',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Enable and configure payment method rule configurations.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/payment-methods',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
