<?php
/**
 * @file
 * menu_link.6c22923f2f483a5d53759b5d2cd965d3deb1b68b.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/order',
  'link_title' => 'Order settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure general order settings, fields, and displays.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/order',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
