<?php
/**
 * @file
 * menu_link.01ca29139cbd9a078a0af9542559f385b78e6dd7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/checkout',
  'link_title' => 'Checkout settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Customize the checkout form and configure checkout rules.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/checkout',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
