<?php
/**
 * @file
 * menu_link.56df9918e0fd2a5eb5fd37f3a8df821b9947c4a2.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/22',
  'link_title' => 'Battery Products Other',
  'menu_name' => 'menu-product-categories',
  'weight' => '4',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery Products Other',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$dependencies = array(
  'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f' => 'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$optional = array();

$modules = array();
