<?php
/**
 * @file
 * menu_link.f25d780e0536a91cbff7e29eaa24f0f2c3fc0abe.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/products/add/pop-item',
  'link_title' => 'Create !name',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'POP item',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/products/add/pop-item',
  'parent_identifier' => '50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$dependencies = array(
  'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8' => 'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$optional = array();

$modules = array();
