<?php
/**
 * @file
 * menu_link.f663af7cab498a6b7a91bc85afb53246a2231cd5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/mail-logger',
  'link_title' => 'Outgoing Mail log',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View Mails that have been sent from this site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/reports/mail-logger',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
