<?php
/**
 * @file
 * menu_link.599cf5a1654845727b8f854c371cdcc873f7caf4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/content',
  'link_title' => 'Generate content',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of nodes and comments. Optionally delete current items.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/content',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
