<?php
/**
 * @file
 * menu_link.92f5cb0effcfc0fe22b5ea89c54d0d1f6fa12a30.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/menu',
  'link_title' => 'Generate menus',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of menus and menu links. Optionally delete current menus.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/menu',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
