<?php
/**
 * @file
 * menu_link.a8e140c682d74713a878f5ee759f11f55f5d3682.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/41',
  'link_title' => 'STIHL Cutquik',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'STIHL Cutquik',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'f085bd32cbd571878f2f5826c229383660d7f32e',
);

$dependencies = array(
  'menu_link.f085bd32cbd571878f2f5826c229383660d7f32e' => 'menu_link.f085bd32cbd571878f2f5826c229383660d7f32e',
);

$optional = array();

$modules = array();
