<?php
/**
 * @file
 * menu_link.d5508f01599b73eae7b8721cf3b270683db5d39e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/20',
  'link_title' => 'Gasoline Chain Saws',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gasoline Chain Saws',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '44036451b4abc996252b4f14d9129fb79e27b833',
);

$dependencies = array(
  'menu_link.44036451b4abc996252b4f14d9129fb79e27b833' => 'menu_link.44036451b4abc996252b4f14d9129fb79e27b833',
);

$optional = array();

$modules = array();
