<?php
/**
 * @file
 * menu_link.00bd33e6e9d914fc062ccdd9f6c5f7022d9c6066.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/28',
  'link_title' => 'Gearbox Attachments',
  'menu_name' => 'menu-product-categories',
  'weight' => '-46',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gearbox Attachments',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => 'ffbe2501719ec189b88398837891ccef024e3ea9',
);

$dependencies = array(
  'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9' => 'menu_link.ffbe2501719ec189b88398837891ccef024e3ea9',
);

$optional = array();

$modules = array();
