<?php
/**
 * @file
 * menu_link.fa10b8c50bf99ce0d9f4ac2c750daeaabbdf57ff.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/34',
  'link_title' => 'Hedge Trimmers Extended',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Hedge Trimmers Extended',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '785e56549281adf49a8a4025c5fe14d17f05610a',
);

$dependencies = array(
  'menu_link.785e56549281adf49a8a4025c5fe14d17f05610a' => 'menu_link.785e56549281adf49a8a4025c5fe14d17f05610a',
);

$optional = array();

$modules = array();
