<?php
/**
 * @file
 * menu_link.785e56549281adf49a8a4025c5fe14d17f05610a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/11',
  'link_title' => 'Hedge Trimmers',
  'menu_name' => 'menu-product-categories',
  'weight' => '-43',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Hedge Trimmers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
