<?php
/**
 * @file
 * menu_link.1247fcc16a95d9001f31cad22c409c53ad6c0c16.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/views-plugins',
  'link_title' => 'Views plugins',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Overview of plugins used in all views.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/reports/views-plugins',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
