<?php
/**
 * @file
 * menu_link.f971b6e4aed015979dfc9af04d93dbef418e15f3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/preview-image-status',
  'link_title' => 'Preview Image Status',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View a list of products without hang tag preview images.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/preview-image-status',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
