<?php
/**
 * @file
 * menu_link.f085bd32cbd571878f2f5826c229383660d7f32e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/14',
  'link_title' => 'Cut-Off Machines',
  'menu_name' => 'menu-product-categories',
  'weight' => '-40',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Cut-Off Machines',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
