<?php
/**
 * @file
 * menu_link.f93b4651c36ac5144ce98e2e53c46d99336fcee3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/25',
  'link_title' => 'Battery Accessories – Backpack Batteries',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Battery Accessories – Backpack Batteries',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$dependencies = array(
  'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f' => 'menu_link.68b4e52732d3952a11424a457d8c53ea1335c41f',
);

$optional = array();

$modules = array();
