<?php
/**
 * @file
 * menu_link.6432591b5da5c73991566e64cb9fa684e56051a4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/9',
  'link_title' => 'Blowers and Shredder Vacs',
  'menu_name' => 'menu-product-categories',
  'weight' => '-45',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Blowers and Shredder Vacs',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
