<?php
/**
 * @file
 * menu_link.744064087d27cc5b3d5d229b08c3f087b7848913.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/user',
  'link_title' => 'Generate users',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of users. Optionally delete current users.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/user',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
