<?php
/**
 * @file
 * menu_link.52c158c9431d032273f8c4a37faad035da14307e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/charts',
  'link_title' => 'Default chart configuration',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Set the default library, behavior, and style of charts.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/content/charts',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
