<?php
/**
 * @file
 * menu_link.43721b03b93776645d62f503b37d2588a45a30f5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/5',
  'link_title' => 'Support',
  'menu_name' => 'user-menu',
  'weight' => '-46',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'node/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.user_menu' => 'menu.user_menu',
);

$optional = array();

$modules = array();
