<?php
/**
 * @file
 * menu_link.c5ba5ee2399ab31858a5a9466382c3031fd38fa4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'cart/my',
  'link_title' => 'Shopping cart (# items)',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'cart/my',
  'parent_identifier' => '56db935fc467bf1e1342e1663804060f126e13cf',
);

$dependencies = array(
  'menu_link.56db935fc467bf1e1342e1663804060f126e13cf' => 'menu_link.56db935fc467bf1e1342e1663804060f126e13cf',
);

$optional = array();

$modules = array();
