<?php
/**
 * @file
 * menu_link.c60964d8d9e3ec0d7d70ed568fcba3389998f7d9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/45',
  'link_title' => 'Precision Series Hand Tools',
  'menu_name' => 'menu-product-categories',
  'weight' => '-49',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Precision Series Hand Tools',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '632fa885c0f607cd192898d89664c9a8e34d0f0e',
);

$dependencies = array(
  'menu_link.632fa885c0f607cd192898d89664c9a8e34d0f0e' => 'menu_link.632fa885c0f607cd192898d89664c9a8e34d0f0e',
);

$optional = array();

$modules = array();
