<?php
/**
 * @file
 * menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config',
  'link_title' => 'Configuration',
  'menu_name' => 'management',
  'weight' => '50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure settings and business rules for your store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config',
  'parent_identifier' => 'fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$dependencies = array(
  'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5' => 'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$optional = array();

$modules = array();
