<?php
/**
 * @file
 * menu_link.b923a5a4a98929732c95395688de7e04242ce2e6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'workflow',
  'link_title' => 'Workflow',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Your workflow dashboard',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'workflow',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
