<?php
/**
 * @file
 * menu_link.62d546ceb3b00be634362d77377b3f3aa86e5acf.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/30',
  'link_title' => 'Bed Redefiner',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Bed Redefiner',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '9053248a69ee189e50eaba50ffeb0383ef17c3c0',
);

$dependencies = array(
  'menu_link.9053248a69ee189e50eaba50ffeb0383ef17c3c0' => 'menu_link.9053248a69ee189e50eaba50ffeb0383ef17c3c0',
);

$optional = array();

$modules = array();
