<?php
/**
 * @file
 * menu_link.87a04bf98c56d1d125f7edc937ef8b47b2384e2d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/stihl/orders',
  'link_title' => 'Orders',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configuration settings for the Stihl Orders module.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/stihl/orders',
  'parent_identifier' => '9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$dependencies = array(
  'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05' => 'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$optional = array();

$modules = array();
