<?php
/**
 * @file
 * menu_link.6520665d5b2aa2974d659411783280f0f4dfa670.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/login_security',
  'link_title' => 'Login Security',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure security settings in the login form submission.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/login_security',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
