<?php
/**
 * @file
 * menu_link.3773cdc3dd9851ad74db911e9a70fba125434474.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'products/search',
  'link_title' => 'Stihl Products',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'products/search',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
