<?php
/**
 * @file
 * menu_link.ae78ba678ea6e038c59693c518b0c06eff0d4cd3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/environment-indicator',
  'link_title' => 'Environment indicators',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer environment indicators.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/environment-indicator',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
