<?php
/**
 * @file
 * menu_link.117d6f6a9fb78f640ac83f13c203f356ef379f1f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/menu/item',
  'link_title' => 'Menu item',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Details about a given menu item.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'devel/menu/item',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
