<?php
/**
 * @file
 * menu_link.b38e571a4fc76c5704e92b2a236c575096e64af0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/line-items/product',
  'link_title' => 'Product',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/line-items/product',
  'parent_identifier' => '6e05437194da9493e221fc0055c67b8d9e8ad1d0',
);

$dependencies = array(
  'menu_link.6e05437194da9493e221fc0055c67b8d9e8ad1d0' => 'menu_link.6e05437194da9493e221fc0055c67b8d9e8ad1d0',
);

$optional = array();

$modules = array();
