<?php
/**
 * @file
 * menu_link.b6e43cfdbace347ed0dd243289f5d6e238fbe7e7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/15',
  'link_title' => 'Concrete Cutters',
  'menu_name' => 'menu-product-categories',
  'weight' => '-39',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Concrete Cutters',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
