<?php
/**
 * @file
 * menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce',
  'link_title' => 'Store',
  'menu_name' => 'management',
  'weight' => '-7',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer your store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
