<?php
/**
 * @file
 * menu_link.95a0ddc3a9c7f2656ecdc2fb0f46f526edea0cac.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/article',
  'link_title' => 'Create Announcements',
  'menu_name' => 'main-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'node/add/article',
  'parent_identifier' => 'd5a2d69870717510ae152eae169a963cba521868',
);

$dependencies = array(
  'menu_link.d5a2d69870717510ae152eae169a963cba521868' => 'menu_link.d5a2d69870717510ae152eae169a963cba521868',
);

$optional = array();

$modules = array();
