<?php
/**
 * @file
 * menu_link.2a29ac72432f2f94d32a67d068f7e8e192d7455a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/purchase-orders',
  'link_title' => 'Purchase orders',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/purchase-orders',
  'parent_identifier' => 'fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$dependencies = array(
  'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5' => 'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$optional = array();

$modules = array();
