<?php
/**
 * @file
 * menu_link.6d5a824465186bd905542769923a9fd44dae07f7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/guardr-core',
  'link_title' => 'Guardr core',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Guardr core settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/guardr-core',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
