<?php
/**
 * @file
 * menu_link.2a3172092eb24b6e2c8a9b6262e3c95776a6ef93.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/theme/registry',
  'link_title' => 'Theme registry',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View a list of available theme functions across the whole site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'devel/theme/registry',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
