<?php
/**
 * @file
 * menu_link.44036451b4abc996252b4f14d9129fb79e27b833.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/5',
  'link_title' => 'Chain Saws',
  'menu_name' => 'menu-product-categories',
  'weight' => '-50',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Chain Saws',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
