<?php
/**
 * @file
 * menu_link.ab7b3f9175aace6553fb302ad22c580fd0d61b2b.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/29',
  'link_title' => 'Gas Edgers',
  'menu_name' => 'menu-product-categories',
  'weight' => '1',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Gas Edgers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '9053248a69ee189e50eaba50ffeb0383ef17c3c0',
);

$dependencies = array(
  'menu_link.9053248a69ee189e50eaba50ffeb0383ef17c3c0' => 'menu_link.9053248a69ee189e50eaba50ffeb0383ef17c3c0',
);

$optional = array();

$modules = array();
