<?php
/**
 * @file
 * menu_link.d18733fb25c12c647f373fcf80ae86ca014332c1.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/views',
  'link_title' => 'Views',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage customized lists of content.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/views',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
