<?php
/**
 * @file
 * menu_link.2b34af0ccb24de49100e6bc9b645c42c128ac5de.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/run-cron',
  'link_title' => 'Run cron',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'devel/run-cron',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
