<?php
/**
 * @file
 * menu_link.d0f6f98c3b9bfc6101800a85d8c59df8c4dddf87.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'orders/new',
  'link_title' => 'Create Order',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'orders/new',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
