<?php
/**
 * @file
 * menu_link.bff0fce674c0ea389f4a0f76cf5b16d8045e435c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/products/add/evergreen',
  'link_title' => 'Create !name',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'POP items that will be available year round.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/products/add/evergreen',
  'parent_identifier' => '50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$dependencies = array(
  'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8' => 'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$optional = array();

$modules = array();
