<?php
/**
 * @file
 * menu_link.88c92abcdcfe60e6da31c5672c0823f9188c02fb.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/features',
  'link_title' => 'Features',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage features.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/features',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
