<?php
/**
 * @file
 * menu_link.262c490fbc758bd405a006317b3931465739e2fa.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/46',
  'link_title' => 'Precision Series Hand Tools B',
  'menu_name' => 'menu-product-categories',
  'weight' => '-50',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Precision Series Hand Tools B',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '632fa885c0f607cd192898d89664c9a8e34d0f0e',
);

$dependencies = array(
  'menu_link.632fa885c0f607cd192898d89664c9a8e34d0f0e' => 'menu_link.632fa885c0f607cd192898d89664c9a8e34d0f0e',
);

$optional = array();

$modules = array();
