<?php
/**
 * @file
 * menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/stihl',
  'link_title' => 'Stihl',
  'menu_name' => 'management',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Stihl tools.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/stihl',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
