<?php
/**
 * @file
 * menu_link.184dad6279c96b90c2a0a97d329cf7f5854e612e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/product',
  'link_title' => 'Generate products',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of products. Optionally delete current products.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/product',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
