<?php
/**
 * @file
 * menu_link.d540322c3abca66222696c3c502663b9dddb27ef.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'mysessions',
  'link_title' => 'My sessions',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'mysessions',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
