<?php
/**
 * @file
 * menu_link.211ce91c9055c85e1ffda04115d0a8611ccf7897.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/permission_watchdog',
  'link_title' => 'Permission watchdog',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Logs changes to role permissions.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/permission_watchdog',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
