<?php
/**
 * @file
 * menu_link.9053248a69ee189e50eaba50ffeb0383ef17c3c0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/8',
  'link_title' => 'Edgers and Bed Redefiners',
  'menu_name' => 'menu-product-categories',
  'weight' => '-46',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Edgers and Bed Redefiners',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
