<?php
/**
 * @file
 * menu_link.3c051971d6cc321384a9d7bd84311f0293f55c25.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/webform',
  'link_title' => 'Webform',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Create a new form or questionnaire accessible to users. Submission results and statistics are recorded and accessible to privileged users.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'node/add/webform',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
