<?php
/**
 * @file
 * menu_link.498fdfd6149a82421e957b44132772b880112d60.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'orders/new',
  'link_title' => 'Create Hangtag Order',
  'menu_name' => 'main-menu',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Create hangtag orders',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'orders/new',
  'parent_identifier' => 'd5a2d69870717510ae152eae169a963cba521868',
);

$dependencies = array(
  'menu_link.d5a2d69870717510ae152eae169a963cba521868' => 'menu_link.d5a2d69870717510ae152eae169a963cba521868',
);

$optional = array();

$modules = array();
