<?php
/**
 * @file
 * menu_link.ec7ecd22e5d3c24ea0890dd26f0ae6fb773e9b6e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/orders',
  'link_title' => 'Orders',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage orders in the store.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/orders',
  'parent_identifier' => 'fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$dependencies = array(
  'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5' => 'menu_link.fcee25bbf2615e9ce5f299b1e12731d62f6e78b5',
);

$optional = array();

$modules = array();
