<?php
/**
 * @file
 * menu_link.cb5f25624b6bc601225aa599005593c2adbef3f7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'branch-distributor-profile',
  'link_title' => 'My Distributor Profile',
  'menu_name' => 'user-menu',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'branch-distributor-profile',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.user_menu' => 'menu.user_menu',
);

$optional = array();

$modules = array();
