<?php
/**
 * @file
 * menu_link.d195507b88c231e105bc19a7253cbe5d30bd47d7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/stihl/stihl-pricing-years',
  'link_title' => 'Stihl Order Pricing Years',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage pricing years',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/stihl/stihl-pricing-years',
  'parent_identifier' => '9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$dependencies = array(
  'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05' => 'menu_link.9fa5806f7fd85f3ab46e8f9ef442f44c9c6f4f05',
);

$optional = array();

$modules = array();
