<?php
/**
 * @file
 * menu_link.56db935fc467bf1e1342e1663804060f126e13cf.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'cart',
  'link_title' => 'Shopping cart',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'cart',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
