<?php
/**
 * @file
 * menu_link.a1cad6ae24abd81642afe28d415a86f890b3eb81.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/menu/manage/menu-product-categories',
  'link_title' => 'Product Categories',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'admin/structure/menu/manage/%',
  'parent_identifier' => '3111902c1834b75b83b11362f105c436d64db94a',
);

$dependencies = array(
  'menu_link.3111902c1834b75b83b11362f105c436d64db94a' => 'menu_link.3111902c1834b75b83b11362f105c436d64db94a',
);

$optional = array();

$modules = array();
