<?php
/**
 * @file
 * menu_link.96c96d5446c0b863ebb7b8e399bc0ac875d785e7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/products/add/product',
  'link_title' => 'Create !name',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'A basic product type.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/products/add/product',
  'parent_identifier' => '50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$dependencies = array(
  'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8' => 'menu_link.50926bda2f00bd150d3d2dfcb1b3d4ecb9188ae8',
);

$optional = array();

$modules = array();
