<?php
/**
 * @file
 * menu_link.ba1877e48fe5a5c19d58d66fa346183214c96b43.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/commerce/config/currency',
  'link_title' => 'Currency settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the default currency and display settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/commerce/config/currency',
  'parent_identifier' => 'd12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$dependencies = array(
  'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3' => 'menu_link.d12b7e30ea6d10eaa0d952050a70946b0e334fd3',
);

$optional = array();

$modules = array();
