<?php
/**
 * @file
 * menu_link.2691b540f8d0fdf80c12051e370555491900ee97.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/elements',
  'link_title' => 'Hook_elements()',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View the active form/render elements for this site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'devel/elements',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
