<?php
/**
 * @file
 * menu_link.98a4a136c1c17c98570a962c1b2870c5a4e3fae5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/36',
  'link_title' => 'Pole Pruners',
  'menu_name' => 'menu-product-categories',
  'weight' => '0',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Pole Pruners',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '513dff1d70c1e3de98f4dfe12defbe8d79caa919',
);

$dependencies = array(
  'menu_link.513dff1d70c1e3de98f4dfe12defbe8d79caa919' => 'menu_link.513dff1d70c1e3de98f4dfe12defbe8d79caa919',
);

$optional = array();

$modules = array();
