<?php
/**
 * @file
 * menu_link.6fd38fadc781b5aeb7149e7af421c29de7a0ec38.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/32',
  'link_title' => 'Backpack Blowers',
  'menu_name' => 'menu-product-categories',
  'weight' => '-50',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Backpack Blowers',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => '6432591b5da5c73991566e64cb9fa684e56051a4',
);

$dependencies = array(
  'menu_link.6432591b5da5c73991566e64cb9fa684e56051a4' => 'menu_link.6432591b5da5c73991566e64cb9fa684e56051a4',
);

$optional = array();

$modules = array();
