<?php
/**
 * @file
 * menu_link.aa7f303b8115fb0fdf1c5deabd155cdd63b81346.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/context',
  'link_title' => 'Context',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Associate menus, views, blocks, etc. with different contexts to structure your site.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/context',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
