<?php
/**
 * @file
 * menu_link.8c388703ec6e4569df2004641764a0b0161761f1.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/stihl-pricing',
  'link_title' => 'Stihl Distributor product pricing',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage product pricing for distributors',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/stihl-pricing',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
