<?php
/**
 * @file
 * menu_link.0d9927d81e34776738a6beba028509f0184083bb.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/menu/manage/menu-pop-catalog',
  'link_title' => 'POP Catalog',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'admin/structure/menu/manage/%',
  'parent_identifier' => '3111902c1834b75b83b11362f105c436d64db94a',
);

$dependencies = array(
  'menu_link.3111902c1834b75b83b11362f105c436d64db94a' => 'menu_link.3111902c1834b75b83b11362f105c436d64db94a',
);

$optional = array();

$modules = array();
