<?php
/**
 * @file
 * menu_link.38cc133fc37d7e1e7360f87222ef811f86bf9697.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/realname',
  'link_title' => 'Real name',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Use tokens to configure how user names are displayed.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/realname',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
