<?php
/**
 * @file
 * menu_link.648e09ee414d4ab329cf81b066bea724e0c6dced.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/slack/test',
  'link_title' => 'Send a message',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Allows to send a test message to the Slack.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/services/slack/test',
  'parent_identifier' => '78da529aecb057f155447c89eaef990088f294cf',
);

$dependencies = array(
  'menu_link.78da529aecb057f155447c89eaef990088f294cf' => 'menu_link.78da529aecb057f155447c89eaef990088f294cf',
);

$optional = array();

$modules = array();
