<?php
/**
 * @file
 * menu_link.3a8a04a77a36cb951da0f3a6e93d3f3e886c6a15.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/taxonomy',
  'link_title' => 'Generate terms',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of terms. Optionally delete current terms.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/generate/taxonomy',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
