<?php
/**
 * @file
 * menu_link.632fa885c0f607cd192898d89664c9a8e34d0f0e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'taxonomy/term/17',
  'link_title' => 'Hand Tools',
  'menu_name' => 'menu-product-categories',
  'weight' => '-37',
  'expanded' => '1',
  'options' => array(
    'attributes' => array(
      'title' => 'Hand Tools',
    ),
  ),
  'router_path' => 'taxonomy/term/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_product_categories' => 'menu.menu_product_categories',
);

$optional = array();

$modules = array();
