<?php
/**
 * @file
 * menu_link.60827e33c32c746f5a99465382a4b809b47cbdc5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/ejectorseat',
  'link_title' => 'Ejector Seat settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure Ejector Seat options.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/ejectorseat',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
