<?php
/**
 * @file
 * menu_link.27dee6bbf254422a79524f28608c32e840f70a7c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/trigger',
  'link_title' => 'Triggers',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure when to execute actions.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/structure/trigger',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
