<?php
/**
 * @file
 * menu_link.c17238ed7a952fa4c552b7a07a51ddf4fbb220a3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/jquery_update',
  'link_title' => 'jQuery Update',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure settings related to the jQuery upgrade, the library path and compression.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/development/jquery_update',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
