<?php
/**
 * @file
 * menu_link.38f6a252c3ec5dd1f9b70a77b88c7d25fd131f33.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/date/date_popup',
  'link_title' => 'Date Popup',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the Date Popup settings.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/date/date_popup',
  'parent_identifier' => '36d59b72fee53ab0ef17a0ee5f8767189e5a9b6f',
);

$dependencies = array(
  'menu_link.36d59b72fee53ab0ef17a0ee5f8767189e5a9b6f' => 'menu_link.36d59b72fee53ab0ef17a0ee5f8767189e5a9b6f',
);

$optional = array();

$modules = array();
