<?php
/**
 * @file
 * menu_link.151b8306bc915a904256fab26540867443d7a190.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/session-limit',
  'link_title' => 'Session limit',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure session limits.',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'admin/config/people/session-limit',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
