<?php
/**
 * @file
 * variable.memcache_wildcard_flushes.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'memcache_wildcard_flushes',
  'content' => array(
    'cache' => array(
      'context' => array(
        7 => 1632672277,
      ),
      'plugins' => array(
        15 => 1632672277,
      ),
      'entity_' => array(
        21 => 1632672277,
        12 => 1632672277,
      ),
      'search_' => array(
        37 => 1632672277,
        33 => 1632672277,
      ),
      'theme_r' => array(
        14 => 1632672277,
      ),
      'node_ty' => array(
        11 => 1632672277,
      ),
      'ctools_' => array(
        20 => 1632672268,
      ),
      'schema:' => array(
        7 => 1632672277,
      ),
    ),
    'cache_menu' => array(
      'admin_menu:' => array(
        11 => 1632684029,
      ),
      'links:manag' => array(
        17 => 1632748854,
      ),
      'links:devel' => array(
        12 => 1631896923,
      ),
      'links:navig' => array(
        17 => 1631896923,
      ),
      'links:menu-' => array(
        23 => 1632748196,
      ),
      'links:user-' => array(
        16 => 1632498711,
      ),
      'links:main-' => array(
        16 => 1632745281,
      ),
    ),
    'cache_search_api_solr' => array(
      'stihl_prod' => array(
        10 => 1621469249,
      ),
    ),
    'cache_field' => array(
      'field_info:' => array(
        11 => 1631742083,
      ),
      'field_info_' => array(
        17 => 1631742083,
      ),
    ),
    'cache_rules' => array(
      'comp_' => array(
        5 => 1631563476,
      ),
      'event' => array(
        6 => 1631567639,
      ),
      'rules' => array(
        21 => 1631567639,
      ),
    ),
    'cache_views_data' => array(
      'pop_orders:' => array(
        11 => 1632749292,
      ),
      'pop_catalog' => array(
        12 => 1632747967,
      ),
      'commerce_pr' => array(
        18 => 1632749926,
      ),
    ),
    'cache_views' => array(
      'views_block_items:' => array(
        18 => 1632748194,
      ),
      'ctools_export:view' => array(
        36 => 1632748194,
        38 => 1631139946,
        35 => 1632749622,
        42 => 1632750199,
      ),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
