<?php
/**
 * @file
 * variable.field_bundle_settings_user__user.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_user__user',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'password_policy' => array(
          'weight' => '0',
        ),
        'account' => array(
          'weight' => '-10',
        ),
        'timezone' => array(
          'weight' => '6',
        ),
        'picture' => array(
          'weight' => '5',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
