<?php
/**
 * @file
 * variable.pricing_update_api_report.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'pricing_update_api_report',
  'content' => array(
    1 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    4 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    2 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    5 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    3 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    6 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    9 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    7 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    10 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    8 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    11 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
    22 => array(
      0 => 'HLKM0STRAI',
      1 => 'HLKM0STRAI',
      2 => 'AR3000',
      3 => 'AR3000',
      4 => 'AR2000',
      5 => 'AR2000',
      6 => 'HLKM145ADJ',
      7 => 'HLKM145ADJ',
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
