<?php
/**
 * @file
 * variable.theme_seven_settings.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'theme_seven_settings',
  'content' => array(
    'default_logo' => 1,
    'logo_path' => '',
    'default_favicon' => 1,
    'favicon_path' => '',
    'favicon_mimetype' => 'image/vnd.microsoft.icon',
    'toggle_logo' => 1,
    'toggle_favicon' => 1,
    'toggle_name' => 1,
    'toggle_slogan' => 1,
    'toggle_node_user_picture' => 1,
    'toggle_comment_user_picture' => 1,
    'toggle_comment_user_verification' => 1,
    'toggle_main_menu' => 1,
    'toggle_secondary_menu' => 1,
    'shortcut_module_link' => '1',
    'logo' => 'http://stihl.dev/themes/seven/logo.png',
    'favicon' => 'http://stihl.dev/misc/favicon.ico',
    'jquery_update_jquery_version' => 'default',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
