<?php
/**
 * @file
 * variable.user_mail_register_pending_approval_body.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'user_mail_register_pending_approval_body',
  'content' => 'Thank you for registering at [site:name]. Your application for an account is currently pending approval. Once it has been approved, you will receive another e-mail containing information about how to log in, set your password, and other details.


--  [site:name] team',
);

$dependencies = array();

$optional = array();

$modules = array();
