<?php
/**
 * @file
 * variable.views_block_hashes.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'views_block_hashes',
  'content' => array(
    '2eba56fe490c65995c46163c8a2370ab' => 'commerce_reports_products-chart_revenue',
    '31eccd6666389cf554f290e91ef9848a' => 'commerce_reports_products-chart_quantity',
    'f3f98e42ba2d4d3103b95e9199cf48fe' => 'commerce_reports_customers-chart_revenue',
    'c4b82619a01ea13a002f9a56cf7aa611' => 'commerce_reports_customers-chart_orders',
    'c143b512518b3a7c6b30be35b192abbf' => 'commerce_reports_customer_map-billing_profiles_block',
    '5efb68bd488bc78cae2aac5b8ddc29a6' => 'commerce_reports_customer_map-shipping_profiles_block',
    'e5caeb6059c44dfa5008c4ff7c6f04be' => 'commerce_reports_customer_statistics-customer_statistics',
    'cc437fbe6b867b448dc946fd925800a3' => 'commerce_reports_sales-chart_year',
    '1127e4706efe2c1eb8537a65a644e572' => 'commerce_reports_sales-chart_month',
    'd70fc459675538d56c73a9f90574211a' => 'commerce_reports_sales-chart_week',
    'ff7824695a12b49a79aee7d394cbd917' => 'commerce_reports_sales_overview-today',
    '1a260a710ed0ccc9e8175e7301e597fe' => 'commerce_reports_sales_overview-yesterday',
    '724c01e6b3c93b66c793ff63f7402697' => 'commerce_reports_sales_overview-month',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
