<?php
/**
 * @file
 * variable.inactive_user_block_warn_text.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'inactive_user_block_warn_text',
  'content' => 'We haven\'t seen you at %sitename since %lastaccess, and we miss you!  This automatic message is to warn you that your account will be disabled in %period unless you come back and visit us before that time.

Please visit us at %siteurl.

Sincerely,
  %sitename team',
);

$dependencies = array();

$optional = array();

$modules = array();
