<?php
/**
 * @file
 * variable.configuration_exclude_configurations.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'configuration_exclude_configurations',
  'content' => 'permission.access_rules_debug
variable.block_cache
variable.cache
variable.cache_class_cache_ctools_css
variable.cache_lifetime
variable.captcha_placement_map_cache
variable.configuration_remote_server
variable.cron_key
variable.cron_last
variable.css_js_query_string
variable.ctools_last_cron
variable.dblog_row_limit
variable.drupal_css_cache_files
variable.drupal_js_cache_files
variable.drupal_private_key
variable.entity_cache_tables_created
variable.error_level
variable.file_temporary_path
variable.googleanalytics_account
variable.googleanalytics_cache
variable.less_dir
variable.maintenance_mode
variable.menu_masks
variable.module_filter_recent_modules
variable.node_cron_last
variable.page_cache_maximum_age
variable.preprocess_css
variable.preprocess_js
variable.rules_debug
variable.rules_debug_log
variable.rules_debug_region_dbb
variable.rules_debug_region_seven
variable.rules_log_errors
variable.tracking__active_tab
variable.update_last_check
variable.update_last_email_notification
variable.xautoload_cache_lazy
variable.xautoload_cache_prefix
variable.xautoload_cache_types
variable.xautoload_replace_core',
);

$dependencies = array();

$optional = array();

$modules = array();
